/* 
Tabel 2.b Mahasiswa Asing 
NOTES :  
TS-2(2018) 
TS-1(2019) 
TS(2020) 
*/ 
SELECT PROGRAM_STUDI.NOMOR, PROGRAM.PROGRAM||' ' ||JURUSAN.JURUSAN AS "Program Studi", 
       SUM (CASE WHEN MAHASISWA.ANGKATAN=2018 THEN 1 ELSE 0 END) AS "TS-2(2018)",  
       SUM (CASE WHEN MAHASISWA.ANGKATAN=2019 THEN 1 ELSE 0 END) AS "TS-1(2019)",  
       SUM (CASE WHEN MAHASISWA.ANGKATAN=2020 THEN 1 ELSE 0 END) AS "TS(2020)" 
FROM DEPARTEMEN 
INNER JOIN PROGRAM_STUDI ON DEPARTEMEN.NOMOR=PROGRAM_STUDI.DEPARTEMEN
INNER JOIN PROGRAM ON PROGRAM_STUDI.PROGRAM=PROGRAM.NOMOR
INNER JOIN JURUSAN ON PROGRAM_STUDI.JURUSAN=JURUSAN.NOMOR
INNER JOIN KELAS ON PROGRAM.NOMOR=KELAS.PROGRAM AND KELAS.JURUSAN=JURUSAN.NOMOR
INNER JOIN MAHASISWA ON KELAS.NOMOR=MAHASISWA.KELAS
INNER JOIN STATUS ON MAHASISWA.STATUS=STATUS.KODE     
WHERE STATUS.KODE='E' /*KODE E = "Mahasiswa Luar Negeri"*/  
      GROUP BY PROGRAM_STUDI.NOMOR, PROGRAM.PROGRAM, JURUSAN.JURUSAN, PROGRAM_STUDI.GELAR 
ORDER BY PROGRAM_STUDI.NOMOR, PROGRAM.PROGRAM;  
