

/*
Query Percobaan 1
*/
/*
Tabel 2.c Kredit Mata Kuliah
*/
SELECT DISTINCT PROGRAM.PROGRAM||' '||JURUSAN.JURUSAN AS "PROGRAM STUDI", EIS_MATAKULIAH.MATAKULIAH,
EIS_MATAKULIAH.SEMESTER, EIS_MATAKULIAH.JAM, EIS_MATAKULIAH.SKS
FROM PROGRAM_STUDI 
INNER JOIN PROGRAM ON PROGRAM_STUDI.PROGRAM=PROGRAM.NOMOR
INNER JOIN JURUSAN ON PROGRAM_STUDI.JURUSAN=JURUSAN.NOMOR
INNER JOIN DEPARTEMEN ON PROGRAM_STUDI.DEPARTEMEN=DEPARTEMEN.NOMOR
INNER JOIN KELAS ON PROGRAM.NOMOR=KELAS.PROGRAM AND JURUSAN.NOMOR=KELAS.JURUSAN
INNER JOIN MAHASISWA ON KELAS.NOMOR=MAHASISWA.KELAS
INNER JOIN EIS_MATAKULIAH ON PROGRAM.NOMOR=EIS_MATAKULIAH.PROGRAM AND
                             JURUSAN.NOMOR=EIS_MATAKULIAH.JURUSAN AND 
                             KELAS.NOMOR=EIS_MATAKULIAH.KELAS
INNER JOIN MATAKULIAH_JENIS ON EIS_MATAKULIAH.MATAKULIAH_JENIS=MATAKULIAH_JENIS.NOMOR
INNER JOIN EIS_KULIAH ON EIS_MATAKULIAH.NOMOR=EIS_KULIAH.MATAKULIAH AND 
                         KELAS.KELAS=EIS_KULIAH.KELAS
INNER JOIN EIS_NILAI ON EIS_KULIAH.NOMOR=EIS_NILAI.KULIAH 
WHERE EIS_MATAKULIAH.TAHUN=2019 AND 
KELAS.KELAS=1
ORDER BY EIS_MATAKULIAH.SEMESTER ASC;

/*
Tabel 2.c Kredit Mata Kuliah
Keterangan : 
- Skema EIS Tahun 2019 -> KELAS (1,2,3) 
- PROGRAM -> D3
- FILTER PROGRAM.NOMOR NOT IN (4,5,6,8,9,10,11,13,14,15,21,23)
- PROGRAM.NOMOR NOT IN (4=D4, 5=D4MD-1, 6=D4DK-3, 8=D4MD-2, 9=D4MD-3,
                       10=D4LJ, 11=D4DK-4, 13=D4DK, 14=D4LJPJJ, 15=D4VEDC,21=D4PJJ,
                       23=D4IDPLN)
*/
SELECT DISTINCT PROGRAM.PROGRAM||' '||JURUSAN.JURUSAN AS "PROGRAM_STUDI",
       EIS_MATAKULIAH.MATAKULIAH,EIS_MATAKULIAH.SKS
FROM PROGRAM_STUDI 
INNER JOIN PROGRAM ON PROGRAM_STUDI.PROGRAM=PROGRAM.NOMOR
INNER JOIN JURUSAN ON PROGRAM_STUDI.JURUSAN=JURUSAN.NOMOR
INNER JOIN DEPARTEMEN ON PROGRAM_STUDI.DEPARTEMEN=DEPARTEMEN.NOMOR
INNER JOIN KELAS ON PROGRAM.NOMOR=KELAS.PROGRAM AND JURUSAN.NOMOR=KELAS.JURUSAN
INNER JOIN EIS_MATAKULIAH ON PROGRAM.NOMOR=EIS_MATAKULIAH.PROGRAM AND
                             JURUSAN.NOMOR=EIS_MATAKULIAH.JURUSAN AND 
                             KELAS.KELAS=EIS_MATAKULIAH.KELAS
INNER JOIN MATAKULIAH_JENIS ON EIS_MATAKULIAH.MATAKULIAH_JENIS=MATAKULIAH_JENIS.NOMOR
INNER JOIN EIS_KULIAH ON EIS_MATAKULIAH.NOMOR=EIS_KULIAH.MATAKULIAH AND 
                         KELAS.NOMOR=EIS_KULIAH.KELAS
INNER JOIN EIS_NILAI ON EIS_KULIAH.NOMOR=EIS_NILAI.KULIAH 
WHERE EIS_MATAKULIAH.TAHUN=2019 AND 
      PROGRAM.NOMOR IN (3) AND /*D3*/
      JURUSAN.NOMOR IN (4) AND /*Teknik Informatika*/
      MATAKULIAH_JENIS.NOMOR IN(1,2,3,4) AND /*Teori dan Praktikum*/ 
      EIS_MATAKULIAH.SEMESTER=1 AND 
      KELAS.KELAS=1
--GROUP BY PROGRAM.PROGRAM, JURUSAN.JURUSAN
ORDER BY PROGRAM_STUDI;
