/*
Tabel 2.c Kredit Mata Kuliah
Menggunakan Skema EIS_MATAKULIAH.TAHUN=2017, EIS_MATAKULIAH.KELAS IN(1,2,3,4), 
                  EIS_MATAKULIAH.SEMESTER IN(1,2)
*/
SELECT ROW_NUMBER() OVER (ORDER BY PROGRAM.PROGRAM) AS "No.", 
       PROGRAM.PROGRAM||' '||JURUSAN.JURUSAN AS "Program Studi", 
       SUM(CASE WHEN MATAKULIAH_JENIS.NOMOR IN(1,3) THEN EIS_MATAKULIAH.SKS END) AS "Teori", 
       SUM(CASE WHEN MATAKULIAH_JENIS.NOMOR IN(2,4,5,6,7,8) THEN EIS_MATAKULIAH.SKS END) AS "Praktikum", 
       0 AS "Praktik", 
       SUM(CASE WHEN MATAKULIAH_JENIS.NOMOR = 5 THEN EIS_MATAKULIAH.SKS END)AS "PKL"
FROM EIS_MATAKULIAH
     INNER JOIN MATAKULIAH_JENIS ON EIS_MATAKULIAH.MATAKULIAH_JENIS=MATAKULIAH_JENIS.NOMOR
     INNER JOIN EIS_KULIAH ON EIS_MATAKULIAH.NOMOR=EIS_KULIAH.MATAKULIAH 
     INNER JOIN PROGRAM ON EIS_MATAKULIAH.PROGRAM=PROGRAM.NOMOR
     INNER JOIN JURUSAN ON EIS_MATAKULIAH.JURUSAN=JURUSAN.NOMOR
     INNER JOIN KELAS ON EIS_KULIAH.KELAS=KELAS.NOMOR 
WHERE EIS_MATAKULIAH.TAHUN=2017 AND 
      EIS_MATAKULIAH.KELAS IN (1,2,3,4) AND 
      EIS_MATAKULIAH.SEMESTER IN(1,2) AND 
      KELAS.PARAREL='A'
GROUP BY PROGRAM.PROGRAM, JURUSAN.JURUSAN, EIS_MATAKULIAH.TAHUN
ORDER BY PROGRAM.PROGRAM;


/*
Tabel 2.c Kredit Mata Kuliah
Menggunakan Skema PASCA_MATAKULIAH.TAHUN=2019
                  EIS_MATAKULIAH.SEMESTER IN(1,2)
*/
SELECT ROW_NUMBER() OVER (ORDER BY PROGRAM.PROGRAM) AS "No.", 
       PROGRAM.PROGRAM||' '||JURUSAN.JURUSAN AS "Program Studi", 
       /*PASCA_MATAKULIAH.TAHUN, PASCA_KULIAH.TAHUN, PASCA_MATAKULIAH.SEMESTER AS "matakuliah", 
       PASCA_KULIAH.SEMESTER AS "kuliah",KELAS.KODE,*/
       SUM(CASE WHEN PASCA_MATAKULIAH_JENIS.NOMOR IN(1) THEN PASCA_MATAKULIAH.SKS END) AS "Teori", 
       SUM(CASE WHEN PASCA_MATAKULIAH_JENIS.NOMOR IN(2,3) THEN PASCA_MATAKULIAH.SKS END) AS "Praktikum|Tesis", 
       0 AS "Praktik", 
       0 AS "PKL"
FROM PASCA_MATAKULIAH
     INNER JOIN PASCA_MATAKULIAH_JENIS ON PASCA_MATAKULIAH.MATAKULIAH_JENIS=PASCA_MATAKULIAH_JENIS.NOMOR
     INNER JOIN PASCA_KULIAH ON PASCA_MATAKULIAH.NOMOR=PASCA_KULIAH.MATAKULIAH 
     INNER JOIN PROGRAM ON PASCA_MATAKULIAH.PROGRAM=PROGRAM.NOMOR
     INNER JOIN JURUSAN ON PASCA_MATAKULIAH.JURUSAN=JURUSAN.NOMOR
     INNER JOIN KELAS ON PROGRAM.NOMOR=KELAS.PROGRAM AND JURUSAN.NOMOR=KELAS.JURUSAN
WHERE PASCA_MATAKULIAH.TAHUN=2019 AND 
      PASCA_KULIAH.TAHUN IN (2019,2020) AND
      PASCA_MATAKULIAH.SEMESTER IN(1) AND 
      PASCA_KULIAH.SEMESTER IN(1,2) AND
      KELAS.PARAREL='A'
GROUP BY PROGRAM.PROGRAM, JURUSAN.JURUSAN 
/*,PASCA_MATAKULIAH.TAHUN, PASCA_KULIAH.TAHUN, PASCA_MATAKULIAH.SEMESTER, PASCA_KULIAH.SEMESTER,KELAS.KODE*/
ORDER BY PROGRAM.PROGRAM;