/*  
Tabel 3.a.1) Kecukupan Dosen Perguruan Tinggi 

Keterangan : 
PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR 10=S3, 11=S3(Guru Besar), 9=S2
STATUS_PEGAWAI.NOMOR (1=Aktif, 6=Tugas Belajar Dalam Negeri, 7=Tugas Belajar Luar Negeri, 10=Dipekerjakan, 11=Ijin Belajar Dalam Negeri, 12=Ijin Belajar Luar Negeri)
STAFF.NOMOR (4=Dosen,8=Dosen Luar,26=Dosen VEDC,57=Dosen PSDKU Lamongan,59=Dosen PSDKU Sumenep)
*/  
SELECT DEPARTEMEN.NOMOR, DEPARTEMEN.DEPARTEMEN,  
COUNT (DISTINCT CASE WHEN PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR IN (10,11) THEN PEGAWAI.NIP END) AS  "Doktor/Doktor Terapan",
COUNT (DISTINCT CASE WHEN PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR= 9 THEN PEGAWAI.NIP END) AS  "Magister/Magister Terapan", 
'' AS "PROFESI",  
-- Total Jumlah Dosen Pada setiap unit pengelola 
 (COUNT(DISTINCT CASE WHEN PEGAWAI_PENDIDIKAN_TINGKAT.PENDIDIKAN='S3' THEN PEGAWAI.NIP END) +  
  COUNT(DISTINCT CASE WHEN PEGAWAI_PENDIDIKAN_TINGKAT.PENDIDIKAN='S2' THEN PEGAWAI.NIP END)) AS "Jumlah"  
FROM DEPARTEMEN 
 INNER JOIN PROGRAM_STUDI ON DEPARTEMEN.NOMOR=PROGRAM_STUDI.DEPARTEMEN 
 INNER JOIN JURUSAN ON PROGRAM_STUDI.JURUSAN=JURUSAN.NOMOR 
 INNER JOIN PROGRAM ON PROGRAM_STUDI.PROGRAM=PROGRAM.NOMOR 
 INNER JOIN PEGAWAI ON JURUSAN.NOMOR=PEGAWAI.JURUSAN 
 INNER JOIN STAFF ON PEGAWAI.STAFF=STAFF.NOMOR
 INNER JOIN JABATAN_FUNGSIONAL ON PEGAWAI.FUNGSIONAL=JABATAN_FUNGSIONAL.NOMOR 
 INNER JOIN PEGAWAI_PENDIDIKAN_TINGKAT ON PEGAWAI.PENDIDIKAN_TERAKHIR=PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR 
 INNER JOIN STATUS_KARYAWAN ON PEGAWAI.STATUS_KARYAWAN=STATUS_KARYAWAN.NOMOR
 INNER JOIN STATUS_PEGAWAI ON PEGAWAI.STATUS=STATUS_PEGAWAI.NOMOR 
WHERE STATUS_PEGAWAI.NOMOR IN (1,6,7,10,11,12) 
AND STAFF.NOMOR IN(4,8,26,57,58,59)
 GROUP BY DEPARTEMEN.NOMOR, DEPARTEMEN.DEPARTEMEN 
 ORDER BY DEPARTEMEN.NOMOR;  