/*
Tabel 3.c.1 Produktivitas Penelitian Dosen
PENELITIAN.JENIS='penelitian'
PENELITIAN.TAHUN_USULAN TS-2(2019), TS-1(2020), TS(2021)
*/
SELECT 1 AS "Nomor", 'Perguruan tinggi atau mandiri' AS "Sumber Pembiayaan", 
COUNT(DISTINCT CASE WHEN PENELITIAN.TAHUN_USULAN=2019 THEN PENELITIAN.ID END) AS "TS-2(2019)", 
COUNT(DISTINCT CASE WHEN PENELITIAN.TAHUN_USULAN=2020 THEN PENELITIAN.ID END) AS "TS-1(2020)", 
COUNT(DISTINCT CASE WHEN PENELITIAN.TAHUN_USULAN=2021 THEN PENELITIAN.ID END) AS "TS(2021)"
FROM PENELITIAN
INNER JOIN PENELITIAN_TEAM ON PENELITIAN.ID=PENELITIAN_TEAM.PENELITIAN_ID
INNER JOIN SIMLITABMAS_USER ON PENELITIAN_TEAM.USER_ID=SIMLITABMAS_USER.ID
INNER JOIN PEGAWAI ON SIMLITABMAS_USER.PEGAWAI_ID=PEGAWAI.NOMOR
WHERE PENELITIAN.JENIS='penelitian' 
ORDER BY PENELITIAN.ID;
