/*
Tabel 5.b.1 Prestasi Akademik Mahasiswa
Prestasi Akademik = Bidang_Prestasi Penalaran
MAHASISWA_EVENT_BIDANG.BIDANG_PRESTASI 1.PENALARAN
*/
SELECT ROW_NUMBER() OVER (ORDER BY MAHASISWA_EVENT.NOMOR) AS "Nomor",
       MAHASISWA_EVENT.EVENT AS "Nama Kegiatan", 
       MAHASISWA_EVENT.TANGGAL AS "Waktu Penyelenggaraan",
       CASE MAHASISWA_EVENT.SKALA_EVENT 
       WHEN 'N' THEN 'Nasional'
       WHEN 'I' THEN 'Internasional'
       WHEN 'R' THEN 'Riset'
       ELSE MAHASISWA_EVENT.SKALA_EVENT 
       END AS "Tingkat",
       MAHASISWA_EVENT_PESERTA.KETERANGAN AS "Prestasi Yang Dicapai"
FROM MAHASISWA_EVENT_PESERTA
     INNER JOIN MAHASISWA_EVENT ON MAHASISWA_EVENT_PESERTA.MAHASISWA_EVENT=MAHASISWA_EVENT.NOMOR
     INNER JOIN MAHASISWA_EVENT_BIDANG ON MAHASISWA_EVENT.EVENT_BIDANG=MAHASISWA_EVENT_BIDANG.NOMOR
     INNER JOIN MAHASISWA ON MAHASISWA_EVENT_PESERTA.MAHASISWA=MAHASISWA.NOMOR
WHERE MAHASISWA_EVENT_BIDANG.NOMOR=1
ORDER BY 1 ASC;