/*
VALIDASI QUERY RELASI TABEL ERD SIAPT(Sistem Akreditasi Perguruan Tinggi)
*/
SELECT DISTINCT PROGRAM.PROGRAM||' '||JURUSAN.JURUSAN AS "PROGRAM STUDI"
FROM PROGRAM_STUDI 
INNER JOIN PROGRAM ON PROGRAM_STUDI.PROGRAM=PROGRAM.NOMOR
INNER JOIN JURUSAN ON PROGRAM_STUDI.JURUSAN=JURUSAN.NOMOR
INNER JOIN DEPARTEMEN ON PROGRAM_STUDI.DEPARTEMEN=DEPARTEMEN.NOMOR
INNER JOIN KELAS ON PROGRAM.NOMOR=KELAS.PROGRAM AND 
                    JURUSAN.NOMOR=KELAS.JURUSAN

/*1. JOIN MAHASISWA*/
INNER JOIN MAHASISWA ON KELAS.NOMOR=MAHASISWA.KELAS 
INNER JOIN STATUS ON MAHASISWA.STATUS=STATUS.KODE
INNER JOIN MAHASISWA_RIWAYAT ON MAHASISWA.NOMOR=MAHASISWA_RIWAYAT.MAHASISWA AND
                                KELAS.NOMOR=MAHASISWA_RIWAYAT.KELAS AND 
                                STATUS.KODE=MAHASISWA_RIWAYAT.STATUS 
INNER JOIN MAHASISWA_RIWAYAT_JENIS ON MAHASISWA_RIWAYAT.MAHASISWA_RIWAYAT_JENIS=MAHASISWA_RIWAYAT_JENIS.NOMOR

/*2. JOIN PEGAWAI*/
INNER JOIN PEGAWAI ON JURUSAN.NOMOR=PEGAWAI.JURUSAN AND 
                      PROGRAM_STUDI.NOMOR=PEGAWAI.PROGRAM_STUDI
INNER JOIN STAFF ON PEGAWAI.STAFF=STAFF.NOMOR
INNER JOIN JABATAN_FUNGSIONAL ON PEGAWAI.FUNGSIONAL=JABATAN_FUNGSIONAL.NOMOR
INNER JOIN STATUS_PEGAWAI ON PEGAWAI.STATUS=STATUS_PEGAWAI.NOMOR
INNER JOIN STATUS_KARYAWAN ON PEGAWAI.STATUS_KARYAWAN=STATUS_KARYAWAN.NOMOR
INNER JOIN PEGAWAI_PENDIDIKAN_TINGKAT ON PEGAWAI.PENDIDIKAN_TERAKHIR=PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR

/*3. JOIN SIMLITABMAS USER*/
INNER JOIN SIMLITABMAS_USER ON PEGAWAI.NOMOR=SIMLITABMAS_USER.PEGAWAI_ID 
INNER JOIN PENELITIAN_TEAM ON SIMLITABMAS_USER.ID=PENELITIAN_TEAM.USER_ID
INNER JOIN PENELITIAN_LOG ON SIMLITABMAS_USER.ID=PENELITIAN_LOG.USER_ID
INNER JOIN PENELITIAN ON PENELITIAN_TEAM.PENELITIAN_ID=PENELITIAN.ID AND
                         PENELITIAN_LOG.PENELITIAN_ID=PENELITIAN.ID
INNER JOIN PENELITIAN_STATUS ON PENELITIAN_LOG.PENELITIAN_STATUS_ID=PENELITIAN_STATUS.ID

/*4. JOIN NAHASISWA_EVENT_PESERTA(PRESTASI MAHASISWA)*/
INNER JOIN MAHASISWA_EVENT_PESERTA ON MAHASISWA.NOMOR=MAHASISWA_EVENT_PESERTA.MAHASISWA
INNER JOIN MAHASISWA_EVENT ON MAHASISWA_EVENT_PESERTA.MAHASISWA_EVENT=MAHASISWA_EVENT.NOMOR
INNER JOIN MAHASISWA_EVENT_BIDANG ON MAHASISWA_EVENT.EVENT_BIDANG=MAHASISWA_EVENT_BIDANG.NOMOR

/*5. JOIN SKEMA EIS_MATAKULIAH*/
INNER JOIN EIS_MATAKULIAH ON PROGRAM.NOMOR=EIS_MATAKULIAH.PROGRAM AND 
                             JURUSAN.NOMOR=EIS_MATAKULIAH.JURUSAN AND 
                             KELAS.KELAS=EIS_MATAKULIAH.KELAS
INNER JOIN MATAKULIAH_JENIS ON EIS_MATAKULIAH.MATAKULIAH_JENIS=MATAKULIAH_JENIS.NOMOR
INNER JOIN EIS_KULIAH ON EIS_MATAKULIAH.NOMOR=EIS_KULIAH.MATAKULIAH AND 
                         KELAS.NOMOR=EIS_KULIAH.KELAS
INNER JOIN EIS_NILAI ON EIS_KULIAH.NOMOR=EIS_NILAI.KULIAH AND 
                        MAHASISWA.NOMOR=EIS_NILAI.MAHASISWA

/*6. JOIN SKEMA MBKM_KULIAH*/
INNER JOIN MBKM_MATAKULIAH ON PROGRAM.NOMOR=MBKM_MATAKULIAH.PROGRAM AND 
                              JURUSAN.NOMOR=MBKM_MATAKULIAH.JURUSAN
INNER JOIN MBKM_KULIAH ON MBKM_MATAKULIAH.NOMOR=MBKM_KULIAH.MATAKULIAH
INNER JOIN MBKM_NILAI ON MBKM_KULIAH.NOMOR=MBKM_NILAI.KULIAH AND 
                         MAHASISWA.NOMOR=MBKM_NILAI.MAHASISWA
