<?php
// Include Koneksi
include "../includes/func.inc.php";
$con=konekDb($db_user, $db_pass);

// Set headers
header('Access-Control-Allow-Origin: *');
header('Content-Type: application/json');

// Check jika request method !== GET maka not allowed
if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    http_response_code(405);
    exit();
}

/* 
 Tabel 3.a.2) Jabatan Akademik Dosen Tetap 

 Keterangan : 
 - PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR 10=S3, 11=S3(Guru Besar), 12=S2
 - JABATAN_FUNGSIONAL.NOMOR 5=Guru Besar, 3=Lektor Kepala, 2=Lektor, 1=Asisten Ahli
 - STAFF.NOMOR 4=Dosen,8=Dosen Luar,26=Dosen VEDC,57=Dosen PSDKU Lamongan59=Dosen PSDKU Sumenep)
 - STATUS_PEGAWAI.NOMOR 1=Aktif, 6=Tugas Belajar Dalam Negeri, 7=Tugas Belajar Luar Negeri, 8=Diperbantukan, 10=Dipekerjakan, 11=Ijin Belajar Dalam Negeri, 12=Ijin Belajar Luar Negeri
 - STATUS_KARYAWAN.NOMOR 4=CPNS,5=PNS
*/ 


$query ='SELECT 
CASE PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR
WHEN 10 THEN 1  
WHEN 11 THEN 2 
WHEN 9 THEN 3 
END AS "Nomor",
CASE PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR
WHEN 10 THEN \'Doktor/Doktor Terapan/Subspesialis\'
WHEN 11 THEN \'Doktor/Doktor Terapan(Guru Besar)/Subspesialis\'
WHEN 9 THEN \'Magister/Magister Terapan/Spesialis\'
END AS "Pendidikan",  
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.NOMOR=5 THEN PEGAWAI.NIP END) AS "Guru Besar", 
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.NOMOR=3 THEN PEGAWAI.NIP END) AS "Lektor Kepala", 
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.NOMOR=2 THEN PEGAWAI.NIP END) AS "Lektor", 
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.NOMOR=1 THEN PEGAWAI.NIP END) AS "Asisten Ahli", 
COUNT(DISTINCT CASE WHEN STAFF.NOMOR IN (4,8,26,57,59) THEN PEGAWAI.NIP END) AS "Tenaga Pengajar"

/*
COUNT(DISTINCT CASE 
WHEN JABATAN_FUNGSIONAL.NOMOR IN (5,3,2,1) THEN PEGAWAI.NIP 
WHEN STAFF.NOMOR IN (4,8,26,57,59) THEN PEGAWAI.NAMA END) AS "Total"
*/

FROM DEPARTEMEN 	 
INNER JOIN PROGRAM_STUDI ON DEPARTEMEN.NOMOR=PROGRAM_STUDI.DEPARTEMEN 
INNER JOIN JURUSAN ON PROGRAM_STUDI.JURUSAN=JURUSAN.NOMOR 
INNER JOIN PROGRAM ON PROGRAM_STUDI.PROGRAM=PROGRAM.NOMOR  
INNER JOIN PEGAWAI ON JURUSAN.NOMOR=PEGAWAI.JURUSAN 	 
INNER JOIN STAFF ON PEGAWAI.STAFF=STAFF.NOMOR
INNER JOIN JABATAN_FUNGSIONAL ON PEGAWAI.FUNGSIONAL=JABATAN_FUNGSIONAL.NOMOR 	  
INNER JOIN PEGAWAI_PENDIDIKAN_TINGKAT ON PEGAWAI.PENDIDIKAN_TERAKHIR=PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR 
INNER JOIN STATUS_KARYAWAN ON PEGAWAI.STATUS_KARYAWAN=STATUS_KARYAWAN.NOMOR
INNER JOIN STATUS_PEGAWAI ON PEGAWAI.STATUS=STATUS_PEGAWAI.NOMOR 
    WHERE STATUS_PEGAWAI.NOMOR IN (1,6,7,8,10,11,12) AND  	 
    STATUS_KARYAWAN.NOMOR IN(4,5) AND   
    PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR IN (9,10,11) AND
    STAFF.NOMOR IN (4,8,26,57,58,59)
GROUP BY PEGAWAI_PENDIDIKAN_TINGKAT.NOMOR, PEGAWAI_PENDIDIKAN_TINGKAT.PENDIDIKAN
ORDER BY 1 ASC';


$stid = oci_parse($con, $query);
oci_execute($stid);

$data = array();

while (($row = oci_fetch_array($stid, OCI_ASSOC+OCI_RETURN_NULLS)) != false) {
    $data[] = $row;
}

oci_free_statement($stid);
oci_close($con);

http_response_code(200);
echo json_encode($data);
?>