<?php
// Include Koneksi
include "../includes/func.inc.php";
$con=konekDb($db_user, $db_pass);

// Set headers
header('Access-Control-Allow-Origin: *');
header('Content-Type: application/json');

// Check jika request method !== GET maka not allowed
if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    http_response_code(405);
    exit();
}

$query = 'SELECT
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.JABATAN=\'Guru Besar\' THEN PEGAWAI.NOMOR END) AS "Guru Besar",
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.JABATAN=\'Lektor Kepala\' THEN PEGAWAI.NOMOR END) AS "Lektor Kepala", 
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.JABATAN=\'Lektor\' THEN PEGAWAI.NOMOR END) AS "Lektor", 
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.JABATAN=\'Asisten Ahli\' THEN PEGAWAI.NOMOR END) AS "Asisten Ahli", 
COUNT(DISTINCT CASE WHEN JABATAN_FUNGSIONAL.JABATAN=\'Tenaga Pengajar\' THEN PEGAWAI.NOMOR END) AS "Tenaga Pengajar",  
COUNT(DISTINCT CASE
    WHEN JABATAN_FUNGSIONAL.JABATAN=\'Guru Besar\' THEN PEGAWAI.NOMOR
    WHEN JABATAN_FUNGSIONAL.JABATAN=\'Lektor Kepala\' THEN PEGAWAI.NOMOR
    WHEN JABATAN_FUNGSIONAL.JABATAN=\'Lektor\' THEN PEGAWAI.NOMOR
    WHEN JABATAN_FUNGSIONAL.JABATAN=\'Asisten Ahli\' THEN PEGAWAI.NOMOR
    WHEN JABATAN_FUNGSIONAL.JABATAN=\'Tenaga Pengajar\' THEN PEGAWAI.NOMOR
    END) AS "Total"
FROM DEPARTEMEN
INNER JOIN PROGRAM_STUDI ON DEPARTEMEN.NOMOR=PROGRAM_STUDI.DEPARTEMEN
INNER JOIN JURUSAN ON PROGRAM_STUDI.JURUSAN=JURUSAN.NOMOR
INNER JOIN PROGRAM ON PROGRAM_STUDI.PROGRAM=PROGRAM.NOMOR
INNER JOIN PEGAWAI ON JURUSAN.NOMOR=PEGAWAI.JURUSAN
INNER JOIN STATUS_PEGAWAI ON PEGAWAI.STATUS=STATUS_PEGAWAI.NOMOR
INNER JOIN STATUS_KARYAWAN ON PEGAWAI.STATUS_KARYAWAN=STATUS_KARYAWAN.NOMOR
INNER JOIN JABATAN_FUNGSIONAL ON PEGAWAI.FUNGSIONAL=JABATAN_FUNGSIONAL.NOMOR
WHERE STATUS_PEGAWAI.STATUS NOT IN (\'Meninggal\', \'Keluar\', \'Pensiun\', \'Pasif\') AND
      STATUS_KARYAWAN.STATUS NOT IN (\'PNS\')
ORDER BY PEGAWAI.NOMOR ASC';

$stid = oci_parse($con, $query);
oci_execute($stid);

$data = array();

while (($row = oci_fetch_array($stid, OCI_ASSOC+OCI_RETURN_NULLS)) != false) {
    $data[] = $row;
}

oci_free_statement($stid);
oci_close($con);

http_response_code(200);
echo json_encode($data);
?>